### PR TITLE
Add license checker

### LINKED ISSUE #462: Continuos Integration - Check license headers
We are currently applying license headers to the code that is part of this project, mainly bash scripts and go files.

It's easy to miss this when creating a new file so we should have this check in our CI.

There are projects like [license-checker](https://github.com/kt3k/license-checker) that allows configuring what to check in a configuration that can be added the project.

### PR DESCRIPTION
**Pull request by rh-hemartin**
## Which Issue(s) this Pull Request Resolves

Resolves #462 

## Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by maruiz93 — APPROVED** [review]

**Comment by ggallen** [comment]
I think we should have a date in our copyright.

**Comment by maruiz93** [comment]
> I think we should have a date in our copyright.

Which kind of date? I see that other popular projects under the same license like bitnami don't put any date: https://github.com/bitnami/charts/blob/main/.licenserc.yaml

**Comment by ggallen** [comment]
> > I think we should have a date in our copyright.
> 
> Which kind of date? I see that other popular projects under the same license like bitnami don't put any date: https://github.com/bitnami/charts/blob/main/.licenserc.yaml

I was looking generally and it seems like copyrights should normally have the year.

https://www.copyrighted.com/blog/copyright-date#:~:text=Does%20the%20copyright%20need%20to,public%2C%20aiding%20in%20legal%20matters.

Also, both Tekton and Knative have years.

- https://github.com/knative/serving/blob/main/pkg/activator/activator.go
- https://github.com/tektoncd/pipeline/blob/main/pkg/apis/config/events.go

The license is different, but I still think we should probably have a date.

**Comment by maruiz93** [comment]
> I was looking generally and it seems like copyrights should normally have the year.

I see, but that will imply having files with 2024 year and new files created next year 2025? Or is it ok if we keep 2024 for all the files including the ones that will be created next year?

**Comment by ggallen** [comment]
> > I was looking generally and it seems like copyrights should normally have the year.
> 
> I see, but that will imply having files with 2024 year and new files created next year 2025? Or is it ok if we keep 2024 for all the files including the ones that will be created next year?

I don't think it matters much. I think we could just always use 2024 as that is when KubeArchive was created.  The year just starts the clock ticking for copyright purposes.  We could also use a range moving forward, and when we update copyrights we could use 2024-2025 if we wanted, or whatever the current year is.

But I'd just go with 2024 for everything.

**Comment by rh-hemartin** [comment]
> I think we should have a date in our copyright.

I think we shouldn't have date in our copyright.

On the OpenSSF badge program (recommended by the CNCF https://contribute.cncf.io/maintainers/security/security-guidelines/#5-openssf-best-practices-badging) they do not require date:

```
The project MUST include a copyright statement in each source file, identifying the copyright holder (e.g., the [project name] contributors). {Met justification} [[copyright_per_file](https://www.bestpractices.dev/en/criteria#2.copyright_per_file)]
```

As justification, they link to a article by the Linux Foundation in which they recommend against adding dates:

https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects

```
By using a common format, the project avoids having to maintain lists of names of the authors or copyright holders, years or ranges of years, and variations on the (c) symbol. 
```

We can flip a coin if we do not agree :rofl:

**Comment by maruiz93** [comment]
@rh-hemartin reason of not having dates is quite backed up so enough reason for me to keep the license as is :)

**Review by mafh314 — APPROVED** [review]

**Pull request merged**
