### PR TITLE
Add instrumentation to the database

### LINKED ISSUE #208: Instrument sql queries for telemetry
Instrument `database/sql` so we get traces further down our chain.

### PR DESCRIPTION
**Pull request by rh-hemartin**
## Which Issue(s) this Pull Request Fixes

Fixes #208 

## Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by rh-hemartin** [comment]
Sink traces:

image

API traces
image

**Review by skoved — APPROVED** [review]

**Comment by maruiz93** [comment]
@rh-hemartin what are you using to test the traces? could we include some instructions of how to replicate that in `DEVELOPMENT.md`? If you are using janitor we could add janitor in helm chart under a specific flag or something along those lines?

**Review by maruiz93 — APPROVED** [review]

**Comment by rh-hemartin** [comment]
> @rh-hemartin what are you using to test the traces? could we include some instructions of how to replicate that in `DEVELOPMENT.md`? If you are using janitor we could add janitor in helm chart under a specific flag or something along those lines?

I'm using Jaeger, let me create an issue to include it and I will post a PR that you can pull and test as well.

**Comment by maruiz93** [comment]
> I'm using Jaeger, let me create an issue to include it and I will post a PR that you can pull and test as well.

Thanks!! (I meant jaeger but my mind messed names on writting.... -.-'')

**Pull request merged**
