### PR TITLE
Configure ApiServerSource using the operator.

### PR DESCRIPTION
**Pull request by ggallen**
Resolves https://github.com/kubearchive/kubearchive/issues/106.

The following things still need to be added, but this could be reviewed now to make things faster.

1. Documentation for configuring a `KubeArchiveConfig` CRD.
2. Fix to handle updates to a `KubeArchiveConfig` CRD.

But things are working now if anyone wants to try it out.

### CODE REVIEW

**Comment by maruiz93** [comment]
Why are you removing templates from the chart in this PR? Don't we need those for the "development" environment?

**Review by rh-hemartin — APPROVED** [review]

**Review by maruiz93 — CHANGES_REQUESTED** [review]
I prefer to understand why removing the templates before merging this

**Comment by ggallen** [comment]
> Why are you removing templates from the chart in this PR? Don't we need those for the "development" environment?

These are now created by the operator.  Look at the code, and you can see by looking at the methods:
```
	sa, err := r.desiredServiceAccount(kaconfig)
	role, err := r.desiredRole(kaconfig)
	binding, err := r.desiredRoleBinding(kaconfig)
	source, err := r.desiredApiServerSource(kaconfig)
```

**Comment by maruiz93** [comment]
> These are now created by the operator. 

So we are going to enforce deploying the operator for testing the sink, right?

**Comment by ggallen** [comment]
> shouldn't we add in the helm chart the CRs filled in a way the apiserversources get configured in a test namespace?

Done!

**Comment by rh-hemartin** [comment]
I think that the `DEVELOPMENT.md` can be updated with the operator image:

```bash
helm install kubearchive charts/kubearchive --create-namespace -n kubearchive \
       --set-string apiServer.image=$(ko build github.com/kubearchive/kubearchive/cmd/api) \
       --set-string sink.image=$(ko build github.com/kubearchive/kubearchive/cmd/sink) \
       --set-string operator.image=$(ko build github.com/kubearchive/kubearchive/cmd/operator)
```

and 

```bash
helm upgrade kubearchive charts/kubearchive -n kubearchive \
    --set-string apiServer.image=$(ko build github.com/kubearchive/kubearchive/cmd/api) \
    --set-string sink.image=$(ko build github.com/kubearchive/kubearchive/cmd/sink) \
    --set-string operator.image=$(ko build github.com/kubearchive/kubearchive/cmd/operator)
```

**Review by maruiz93 — APPROVED** [review]

**Review by skoved — APPROVED** [review]

**Pull request merged**
